config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/katas', to: 'katas#index'
  get '/katas/new', to: 'katas#new'
  get '/katas/show', to: 'katas#show'
  get '/katas/update', to: 'katas#update'
  get '/katas/destroy', to: 'katas#destroy'
  get '/katas/play', to: 'katas#play'

  get '/flashcards', to: 'flashcards#index'
  get '/flashcards/new', to: 'flashcards#new'
  get '/flashcards/show', to: 'flashcards#show'
  get '/flashcards/update', to: 'flashcards#update'
  get '/flashcards/destroy', to: 'flashcards#destroy'
  get '/flashcards/play', to: 'flashcards#play'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flash_card.rb
class FlashCard < ApplicationRecord
end

app/models/kata.rb
class Kata < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @flashcards = FlashCard.all
  end

  def create
  end

  def show
  end

  def update
  end

  def destroy
  end

  def play
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/katas_controller.rb
class KatasController < ApplicationController
  def index
  end

  def create
  end

  def show
    @katas = Kata.all
  end

  def update
  end

  def destroy
  end

  def play
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/katas_helper.rb
module KatasHelper
end

app/views/flashcards/create.html.erb
<h1>Katas#create</h1>
<p>Find me in app/views/katas/create.html.erb</p>

app/views/flashcards/destroy.html.erb
<h1>Katas#destroy</h1>
<p>Find me in app/views/katas/destroy.html.erb</p>

app/views/flashcards/index.html.erb
<div id="flashcardsbody">
<h1>Flash Cards</h1>
<button><%=link_to 'Play', flashcards_play_path%></button>
<button><%=link_to 'View All Flash Cards', flashcards_show_path%></button>
<button><%=link_to 'Create New Flash Card', flashcards_new_path%></button>
<button><%=link_to 'Go Back', root_path%></button>
</div>

app/views/flashcards/play.html.erb
<h1>Katas#play</h1>
<p>Find me in app/views/katas/play.html.erb</p>

app/views/flashcards/show.html.erb
<h1>Katas#show</h1>
<p>Find me in app/views/katas/show.html.erb</p>

app/views/flashcards/update.html.erb
<h1>Katas#update</h1>
<p>Find me in app/views/katas/update.html.erb</p>

app/views/home/index.html.erb
<div id="homebody">

<h1>Home</h1>
<button><%=link_to 'Flashcards', flashcards_path%></button>
<button><%=link_to 'Katas', katas_path%></button>
</div>

app/views/katas/create.html.erb
<h1>Katas#create</h1>
<p>Find me in app/views/katas/create.html.erb</p>

app/views/katas/destroy.html.erb
<h1>Katas#destroy</h1>
<p>Find me in app/views/katas/destroy.html.erb</p>

app/views/katas/index.html.erb
<div id="katasbody">
<h1>Katas</h1>
<button><%=link_to 'Play', katas_play_path%></button>
<button><%=link_to 'View All Katas', katas_show_path%></button>
<button><%=link_to 'Create New Kata', katas_new_path%></button>
<button><%=link_to 'Go Back', root_path%></button>
</div>

app/views/katas/play.html.erb
<h1>Katas#play</h1>
<p>Find me in app/views/katas/play.html.erb</p>

app/views/katas/show.html.erb
<h1>Katas#show</h1>
<p>Find me in app/views/katas/show.html.erb</p>

app/views/katas/update.html.erb
<h1>Katas#update</h1>
<p>Find me in app/views/katas/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeyondLangs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>